name: Character Submission
description: Submit a character preset to the community library
title: "[Character] "
labels: ["character-submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit Your Character
        
        Thank you for contributing to the Elden Ring character library!
        
  - type: input
    id: character-name
    attributes:
      label: Character Name
      description: The name of your character
      placeholder: "e.g., Shadowblade Assassin"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your character's build, playstyle, or lore
      placeholder: "A DEX/INT hybrid focused on stealth and magic..."
    validations:
      required: true
      
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags (e.g., pvp, dex, mage)
      placeholder: "pvp, dex, faith"
      
  - type: dropdown
    id: ng-plus
    attributes:
      label: NG+ Cycle
      options:
        - "NG (First Playthrough)"
        - "NG+"
        - "NG+2"
        - "NG+3"
        - "NG+4"
        - "NG+5"
        - "NG+6"
        - "NG+7+"
    validations:
      required: true
      
  - type: checkboxes
    id: dlc
    attributes:
      label: DLC Requirements
      options:
        - label: "Requires Shadow of the Erdtree DLC"
          
  - type: checkboxes
    id: mods
    attributes:
      label: Modifications
      options:
        - label: "Uses modded items/features"
        
  - type: textarea
    id: zip-file
    attributes:
      label: Character File
      description: Attach the ZIP file generated by the save manager
      placeholder: "Drag and drop your .zip file here"
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Submission Agreement
      options:
        - label: "I confirm this character was created by me and I agree to share it with the community"
          required: true
        - label: "I confirm this character does not contain any inappropriate content"
          required: true